# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6d3d665bd50b6e78e08fe1d7f4263cb690ce2406f02bbc143b47af93a6176eb10b3f81fad5b16e1a610e592087bc91380c27251529c37dac3d78a1376216fb9

test:
  secret_key_base: 56cbcb793531bcdf5181257243875589ff6b5f8e6f6ad9848234e57590a6d8e5a57b396bfcc20963c7592aac0ffd20a1661176228b3ed2a3baa80ee03d3d9d42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
